=== gspandy/eip-frameworks-comparison/eip-frameworks-resources/src/main/resources/order.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.j-labs.pl/blog/order" targetNamespace="http://www.j-labs.pl/blog/order" elementFormDefault="qualified" attributeFormDefault="unqualified">

  <xs:element name="order" type="tns:orderType"/>
  
  <xs:complexType name="orderType">
    <xs:sequence>
      <xs:element name="date" type="xs:date" minOccurs="1" maxOccurs="1"/>
      <xs:element name="client" type="tns:clientType" minOccurs="1" maxOccurs="1"/>
      <xs:element name="items">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="item" type="tns:itemType" minOccurs="1" maxOccurs="3"/>            
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="identifier" type="xs:int" use="required"/>
  </xs:complexType>

  <xs:complexType name="clientType">
    <xs:sequence>
      <xs:element name="name" type="xs:string"/>
      <xs:element name="surname" type="xs:string"/>
      <xs:element name="address" type="xs:string"/>
      <xs:element name="email" type="xs:string"/>
      <xs:element name="phone" type="xs:int"/>
    </xs:sequence>
    <xs:attribute name="identifier" type="xs:int" use="required"/>
  </xs:complexType>
  
  <xs:complexType name="itemType">
    <xs:sequence>
      <xs:element name="name" type="xs:string"/>
      <xs:element name="description" type="xs:string"/>
      <xs:element name="count" type="xs:int"/>
    </xs:sequence>
    <xs:attribute name="identifier" type="xs:int" use="required"/>
  </xs:complexType>

</xs:schema>

=== gspandy/eip-frameworks-comparison/eip-frameworks-test-resources/src/main/resources/invalidOrder.xml
<?xml version="1.0" encoding="UTF-8"?>
<order xmlns="http://www.j-labs.pl/blog/order" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.j-labs.pl/blog/order order.xsd" identifier="123">
  <items>
    <item identifier="1">
      <name>Sony Bravia</name>
      <description>TV set</description>
      <count>1</count>
    </item>
    <item identifier="2">
      <name>HTC 10</name>
      <description>smartphone</description>
      <count>1</count>
    </item>
  </items>
</order>

=== gspandy/eip-frameworks-comparison/eip-frameworks-test-resources/src/main/resources/order.xml
<?xml version="1.0" encoding="UTF-8"?>
<order xmlns="http://www.j-labs.pl/blog/order" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.j-labs.pl/blog/order order.xsd" identifier="375153">
  <date>2016-10-28</date>
  <client identifier="44">
    <name>Paweł</name>
    <surname>Weselak</surname>
    <address>Szlak 77, Kraków</address>
    <email>pawel.weselak@j-labs.pl</email>
    <phone>512262144</phone>
  </client>
  <items>
    <item identifier="1">
      <name>Sony Bravia</name>
      <description>TV set</description>
      <count>1</count>
    </item>
    <item identifier="2">
      <name>HTC 10</name>
      <description>smartphone</description>
      <count>1</count>
    </item>
  </items>
</order>
